-- Add OTP (One-Time Password) fields to claims table for pickup confirmation
-- These fields enable a secure handoff process where:
-- 1. Receiver generates a 6-digit code when ready for pickup
-- 2. Receiver shows this code to the donor at pickup location
-- 3. Donor confirms pickup by entering the code
-- 4. System marks the claim as completed and tracks pickup time

ALTER TABLE claims 
ADD COLUMN pickup_code VARCHAR(6),
ADD COLUMN pickup_code_generated_at TIMESTAMP,
ADD COLUMN picked_up_at TIMESTAMP;

-- Add index on pickup_code for faster lookups during verification
CREATE INDEX idx_claims_pickup_code ON claims(pickup_code) WHERE pickup_code IS NOT NULL;

-- Add comments for documentation
COMMENT ON COLUMN claims.pickup_code IS 'Six-digit OTP code generated by receiver for secure pickup confirmation';
COMMENT ON COLUMN claims.pickup_code_generated_at IS 'Timestamp when the pickup code was generated (code expires after 30 minutes)';
COMMENT ON COLUMN claims.picked_up_at IS 'Timestamp when the donor confirmed successful pickup using the OTP code';
