ALTER TABLE surplus_posts
    ADD COLUMN IF NOT EXISTS impact_co2e_kg DOUBLE PRECISION NULL,
    ADD COLUMN IF NOT EXISTS impact_water_l DOUBLE PRECISION NULL,
    ADD COLUMN IF NOT EXISTS impact_factor_version VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS impact_computed_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS impact_inputs JSONB NULL;
