package com.example.foodflow.util;

import org.junit.jupiter.api.Test;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

class CsvExportUtilsTest {

    @Test
    void writeHelpers_ProduceExpectedCsvSections() {
        StringWriter buffer = new StringWriter();
        PrintWriter writer = new PrintWriter(buffer);
        LocalDateTime exportTime = LocalDateTime.of(2026, 4, 5, 9, 15);

        CsvExportUtils.writeHeader(writer, "Impact Report", exportTime, "DONOR", "Last 30 Days");
        CsvExportUtils.writeSectionHeader(writer, "Overview");
        CsvExportUtils.writeMetric(writer, "Active Users", 42);
        CsvExportUtils.writeNumericMetric(writer, "Weight Saved", 12.5, "kg");
        CsvExportUtils.writePercentageMetric(writer, "Claim Rate", 87.5);
        CsvExportUtils.writeRangeMetric(writer, "Window", 7, 14);
        CsvExportUtils.writeMetadataDisclosure(writer, "v1", "Factors, formulas, and \"notes\"");
        CsvExportUtils.writeFooter(writer);
        writer.flush();

        String csv = buffer.toString();

        assertThat(csv).contains("Impact Report");
        assertThat(csv).contains("Report Generated,Apr 5 2026 at 9:15 AM");
        assertThat(csv).contains("Viewer Role,Food Donor");
        assertThat(csv).contains("Overview,");
        assertThat(csv).contains("Active Users,42");
        assertThat(csv).contains("Weight Saved,12.50 kg");
        assertThat(csv).contains("Claim Rate,87.5%");
        assertThat(csv).contains("Window,7-14");
        assertThat(csv).contains("Factor Version,v1");
        assertThat(csv).contains("Generated by FoodFlow");
        assertThat(csv).contains("\"Factors, formulas, and \"\"notes\"\"\"");
    }

    @Test
    void formattingHelpers_HandleNullsAndKnownLabels() {
        assertThat(CsvExportUtils.formatNumber(null)).isEqualTo("0");
        assertThat(CsvExportUtils.formatNumber(12)).isEqualTo("12");
        assertThat(CsvExportUtils.formatNumber(12.345)).isEqualTo("12.35");

        assertThat(CsvExportUtils.formatDateTime(null)).isEqualTo("N/A");
        assertThat(CsvExportUtils.formatDate(LocalDateTime.of(2026, 4, 5, 9, 15)))
                .isEqualTo("Apr 5 2026");

        assertThat(CsvExportUtils.formatRole(null)).isEqualTo("Unknown");
        assertThat(CsvExportUtils.formatRole("RECEIVER")).isEqualTo("Food Receiver");
        assertThat(CsvExportUtils.formatRole("CUSTOM")).isEqualTo("CUSTOM");
    }

    @Test
    void formatDateRangeLabel_HandlesKnownAndCustomRanges() {
        LocalDateTime start = LocalDateTime.of(2026, 1, 1, 0, 0);
        LocalDateTime end = LocalDateTime.of(2026, 1, 31, 23, 59);

        assertThat(CsvExportUtils.formatDateRangeLabel(null, start, end))
                .isEqualTo("All Time");
        assertThat(CsvExportUtils.formatDateRangeLabel("DAYS_30", start, end))
                .isEqualTo("Last 30 Days (Jan 1 2026 to Jan 31 2026)");
        assertThat(CsvExportUtils.formatDateRangeLabel("CUSTOM", start, end))
                .isEqualTo("CUSTOM (Jan 1 2026 to Jan 31 2026)");
    }

    @Test
    void escapeCsvValue_QuotesOnlyWhenRequired() {
        assertThat(CsvExportUtils.escapeCsvValue(null)).isEmpty();
        assertThat(CsvExportUtils.escapeCsvValue("simple")).isEqualTo("simple");
        assertThat(CsvExportUtils.escapeCsvValue("a,b")).isEqualTo("\"a,b\"");
        assertThat(CsvExportUtils.escapeCsvValue("line\nbreak")).isEqualTo("\"line\nbreak\"");
        assertThat(CsvExportUtils.escapeCsvValue("say \"hi\"")).isEqualTo("\"say \"\"hi\"\"\"");
    }
}
