export const donorTutorialSteps = [
  {
    key: 'dashboard',
    route: '/donor',
    selector: '[data-tour="donor-dashboard-main"]',
    placement: 'bottom',
    title: 'Welcome to FoodFlow',
    text: 'This is your donor dashboard. From here, you can manage your donations and follow what happens next.',
  },
  {
    key: 'impact-dashboard',
    route: '/donor/impact',
    selector: '[data-tour="donor-impact-controls"]',
    placement: 'bottom',
    title: 'See your impact',
    text: 'Your impact dashboard shows how much food you have saved and the difference your donations are making over time.',
  },
  {
    key: 'post-donation',
    route: '/donor/list',
    selector: '[data-tour="donor-post-donation"]',
    placement: 'bottom',
    title: 'Post a donation',
    text: 'Use this action to create a new food donation and make it available to receivers.',
  },
  {
    key: 'chat',
    route: '/donor/messages',
    selector: '[data-tour="donor-chat-area"]',
    placement: 'right',
    title: 'Chat with receivers',
    text: 'Once a donation is claimed, you can use chat to coordinate pickup details and answer questions.',
  },
  {
    key: 'pickup-progress',
    route: '/donor/list',
    selector: '[data-tour="donor-pickup-flow"]',
    placement: 'top',
    title: 'Follow pickup progress',
    text: 'Each donation moves through a pickup flow with statuses so you always know what stage it is in.',
  },
  {
    key: 'done',
    route: '/donor/settings',
    selector: '[data-tour="donor-settings-setup"]',
    placement: 'bottom',
    title: 'Set up your account',
    text: 'Use Language & Region to choose your language, location, and timezone. Calendar Integration lets you sync FoodFlow pickups, and Display Preferences controls how your donation cards look.',
  },
];
