export const getDonorTutorialSteps = t => [
  {
    key: 'welcome',
    route: '/donor',
    selector: null,
    placement: 'center',
    title: t('onboarding.donor.steps.welcome.title'),
    text: t('onboarding.donor.steps.welcome.text'),
  },
  {
    key: 'dashboard',
    route: '/donor/dashboard',
    selector: '[data-tour="donor-dashboard-main"]',
    placement: 'bottom',
    title: t('onboarding.donor.steps.dashboard.title'),
    text: t('onboarding.donor.steps.dashboard.text'),
  },
  {
    key: 'settings',
    route: '/donor/settings',
    selector: '[data-tour="donor-nav-settings"]',
    placement: 'right',
    title: t('onboarding.donor.steps.settings.title'),
    text: t('onboarding.donor.steps.settings.text'),
  },
  {
    key: 'create-donation',
    route: '/donor/list',
    selector: '[data-tour="donor-nav-donate"]',
    placement: 'right',
    title: t('onboarding.donor.steps.createDonation.title'),
    text: t('onboarding.donor.steps.createDonation.text'),
  },
  {
    key: 'ai-donation',
    route: '/donor/ai-donation',
    selector: '[data-tour="donor-ai-donation-main"]',
    placement: 'bottom',
    title: t('onboarding.donor.steps.aiDonation.title'),
    text: t('onboarding.donor.steps.aiDonation.text'),
  },
  {
    key: 'achievements',
    route: '/donor/achievements',
    selector: '[data-tour="donor-nav-achievements"]',
    placement: 'right',
    title: t('onboarding.donor.steps.achievements.title'),
    text: t('onboarding.donor.steps.achievements.text'),
  },
];
