export const getDonorTutorialSteps = t => [
  {
    key: 'dashboard',
    route: '/donor',
    selector: '[data-tour="donor-dashboard-main"]',
    placement: 'bottom',
    title: t('onboarding.donor.steps.dashboard.title'),
    text: t('onboarding.donor.steps.dashboard.text'),
  },
  {
    key: 'impact-dashboard',
    route: '/donor/impact',
    selector: '[data-tour="donor-nav-impact"]',
    placement: 'right',
    title: t('onboarding.donor.steps.impact.title'),
    text: t('onboarding.donor.steps.impact.text'),
  },
  {
    key: 'post-donation',
    route: '/donor/list',
    selector: '[data-tour="donor-nav-donate"]',
    placement: 'right',
    title: t('onboarding.donor.steps.postDonation.title'),
    text: t('onboarding.donor.steps.postDonation.text'),
  },
  {
    key: 'chat',
    route: '/donor/messages',
    selector: '[data-tour="donor-nav-messages"]',
    placement: 'right',
    title: t('onboarding.donor.steps.chat.title'),
    text: t('onboarding.donor.steps.chat.text'),
  },
  {
    key: 'pickup-progress',
    route: '/donor/list',
    selector: '[data-tour="donor-nav-donate"]',
    placement: 'right',
    title: t('onboarding.donor.steps.pickup.title'),
    text: t('onboarding.donor.steps.pickup.text'),
  },
  {
    key: 'done',
    route: '/donor/settings',
    selector: '[data-tour="donor-nav-settings"]',
    placement: 'top',
    title: t('onboarding.donor.steps.setup.title'),
    text: t('onboarding.donor.steps.setup.text'),
  },
];
