export const getReceiverTutorialSteps = t => [
  {
    key: 'browse-donations',
    route: '/receiver',
    selector: '[data-tour="receiver-nav-browse"]',
    placement: 'right',
    title: t('onboarding.receiver.steps.browse.title'),
    text: t('onboarding.receiver.steps.browse.text'),
  },
  {
    key: 'saved-donations',
    route: '/receiver/saved-donations',
    selector: '[data-tour="receiver-nav-saved"]',
    placement: 'right',
    title: t('onboarding.receiver.steps.saved.title'),
    text: t('onboarding.receiver.steps.saved.text'),
  },
  {
    key: 'your-claims',
    route: '/receiver/my-claims',
    selector: '[data-tour="receiver-nav-claims"]',
    placement: 'right',
    title: t('onboarding.receiver.steps.claims.title'),
    text: t('onboarding.receiver.steps.claims.text'),
  },
  {
    key: 'chat',
    route: '/receiver/messages',
    selector: '[data-tour="receiver-nav-messages"]',
    placement: 'left',
    title: t('onboarding.receiver.steps.chat.title'),
    text: t('onboarding.receiver.steps.chat.text'),
  },
  {
    key: 'impact-dashboard',
    route: '/receiver/impact',
    selector: '[data-tour="receiver-nav-impact"]',
    placement: 'right',
    title: t('onboarding.receiver.steps.impact.title'),
    text: t('onboarding.receiver.steps.impact.text'),
  },
  {
    key: 'preferences',
    route: '/receiver/browse',
    selector: '[data-tour="receiver-preferences-entry"]',
    placement: 'left',
    title: t('onboarding.receiver.steps.preferences.title'),
    text: t('onboarding.receiver.steps.preferences.text'),
  },
  {
    key: 'settings',
    route: '/receiver/settings',
    selector: '[data-tour="receiver-settings-entry"]',
    placement: 'left',
    title: t('onboarding.receiver.steps.settings.title'),
    text: t('onboarding.receiver.steps.settings.text'),
  },
  {
    key: 'done',
    route: '/receiver/settings',
    selector: null,
    placement: 'center',
    title: t('onboarding.receiver.steps.done.title'),
    text: t('onboarding.receiver.steps.done.text'),
  },
];
