export const getReceiverTutorialSteps = t => [
  {
    key: 'welcome',
    route: '/receiver',
    selector: null,
    placement: 'center',
    title: t('onboarding.receiver.steps.welcome.title'),
    text: t('onboarding.receiver.steps.welcome.text'),
  },
  {
    key: 'browse-donations',
    route: '/receiver',
    selector: '[data-tour="receiver-browse-main"]',
    placement: 'bottom',
    title: t('onboarding.receiver.steps.browse.title'),
    text: t('onboarding.receiver.steps.browse.text'),
  },
  {
    key: 'settings',
    route: '/receiver/settings',
    selector: '[data-tour="receiver-account-menu"]',
    placement: 'left',
    title: t('onboarding.receiver.steps.settings.title'),
    text: t('onboarding.receiver.steps.settings.text'),
  },
  {
    key: 'claims',
    route: '/receiver/my-claims',
    selector: '[data-tour="receiver-nav-claims"]',
    placement: 'right',
    title: t('onboarding.receiver.steps.claims.title'),
    text: t('onboarding.receiver.steps.claims.text'),
  },
  {
    key: 'messages',
    route: '/receiver/messages',
    selector: '[data-tour="receiver-nav-messages"]',
    placement: 'left',
    title: t('onboarding.receiver.steps.messages.title'),
    text: t('onboarding.receiver.steps.messages.text'),
  },
  {
    key: 'impact',
    route: '/receiver/impact',
    selector: '[data-tour="receiver-nav-impact"]',
    placement: 'right',
    title: t('onboarding.receiver.steps.impact.title'),
    text: t('onboarding.receiver.steps.impact.text'),
  },
  {
    key: 'achievements',
    route: '/receiver/achievements',
    selector: '[data-tour="receiver-nav-achievements"]',
    placement: 'right',
    title: t('onboarding.receiver.steps.achievements.title'),
    text: t('onboarding.receiver.steps.achievements.text'),
  },
];
