package com.example.foodflow.util;

import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Utility class for generating professional CSV exports with FoodFlow branding
 */
public class CsvExportUtils {

    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter
            .ofPattern("MMMM d, yyyy 'at' h:mm a");
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("MMMM d, yyyy");

    /**
     * Write CSV header metadata section with FoodFlow branding
     */
    public static void writeHeader(PrintWriter writer, String reportTitle, LocalDateTime exportTime,
            String viewerRole, String dateRangeLabel) {
        // Branded header
        writer.println("FoodFlow - Impact Report");
        writer.println(reportTitle);
        writer.println();

        // Metadata section
        writer.println("Report Generated," + formatDateTime(exportTime));
        writer.println("Report Type," + reportTitle);
        writer.println("Viewer Role," + formatRole(viewerRole));
        writer.println("Reporting Period," + dateRangeLabel);
        writer.println();
    }

    /**
     * Write section header with visual separator
     */
    public static void writeSectionHeader(PrintWriter writer, String sectionName) {
        writer.println();
        writer.println(sectionName);
        writer.println("---");
    }

    /**
     * Write a metric with consistent formatting
     */
    public static void writeMetric(PrintWriter writer, String metricName, Object value) {
        if (value != null) {
            writer.println("\"" + metricName + "\",\"" + value.toString() + "\"");
        }
    }

    /**
     * Write a numeric metric with unit
     */
    public static void writeNumericMetric(PrintWriter writer, String metricName, Number value, String unit) {
        if (value != null) {
            String formattedValue = formatNumber(value) + (unit != null && !unit.isEmpty() ? " " + unit : "");
            writer.println("\"" + metricName + "\",\"" + formattedValue + "\"");
        }
    }

    /**
     * Write a percentage metric
     */
    public static void writePercentageMetric(PrintWriter writer, String metricName, Double value) {
        if (value != null) {
            writer.println("\"" + metricName + "\",\"" + String.format("%.1f%%", value) + "\"");
        }
    }

    /**
     * Write a range metric (min-max)
     */
    public static void writeRangeMetric(PrintWriter writer, String metricName, Integer min, Integer max) {
        if (min != null && max != null) {
            writer.println("\"" + metricName + "\",\"" + min + " - " + max + "\"");
        }
    }

    /**
     * Write metadata disclosure section
     */
    public static void writeMetadataDisclosure(PrintWriter writer, String factorVersion, String factorDisclosure) {
        writeSectionHeader(writer, "Calculation Methodology");
        if (factorVersion != null) {
            writer.println("\"Factor Version\",\"" + factorVersion + "\"");
        }
        if (factorDisclosure != null) {
            // Escape quotes in disclosure text
            String escaped = factorDisclosure.replace("\"", "\"\"");
            writer.println("\"Methodology Disclosure\",\"" + escaped + "\"");
        }
    }

    /**
     * Write footer with usage notice
     */
    public static void writeFooter(PrintWriter writer) {
        writer.println();
        writer.println("---");
        writer.println("This report was automatically generated by FoodFlow.");
        writer.println("For questions or feedback about this export, contact your FoodFlow administrator.");
    }

    /**
     * Format a number with appropriate decimal places
     */
    public static String formatNumber(Number value) {
        if (value == null) {
            return "0";
        }

        if (value instanceof Integer || value instanceof Long) {
            return value.toString();
        }

        Double doubleValue = value.doubleValue();
        // Use 2 decimal places for prices, weights, etc.
        return String.format("%.2f", doubleValue);
    }

    /**
     * Format a date-time value
     */
    public static String formatDateTime(LocalDateTime dateTime) {
        if (dateTime == null) {
            return "N/A";
        }
        return dateTime.format(DATE_TIME_FORMATTER);
    }

    /**
     * Format a date value
     */
    public static String formatDate(LocalDateTime dateTime) {
        if (dateTime == null) {
            return "N/A";
        }
        return dateTime.format(DATE_FORMATTER);
    }

    /**
     * Format a role to human-readable form
     */
    public static String formatRole(String role) {
        if (role == null) {
            return "Unknown";
        }
        switch (role) {
            case "DONOR":
                return "Food Donor";
            case "RECEIVER":
                return "Food Receiver";
            case "ADMIN":
                return "Administrator";
            default:
                return role;
        }
    }

    /**
     * Format date range label with proper description
     */
    public static String formatDateRangeLabel(String dateRangeEnum, LocalDateTime startDate, LocalDateTime endDate) {
        if (dateRangeEnum == null) {
            return "All Time";
        }

        String rangeLabel = "";
        switch (dateRangeEnum) {
            case "DAYS_7":
                rangeLabel = "Last 7 Days";
                break;
            case "DAYS_30":
                rangeLabel = "Last 30 Days";
                break;
            case "DAYS_60":
                rangeLabel = "Last 60 Days";
                break;
            case "DAYS_365":
                rangeLabel = "Last Year";
                break;
            case "ALL_TIME":
                rangeLabel = "All Time";
                break;
            default:
                rangeLabel = dateRangeEnum;
        }

        if (startDate != null && endDate != null) {
            rangeLabel += " (" + formatDate(startDate) + " to " + formatDate(endDate) + ")";
        }

        return rangeLabel;
    }

    /**
     * Escape CSV value to prevent injection or formatting issues
     */
    public static String escapeCsvValue(String value) {
        if (value == null) {
            return "";
        }
        if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }
}
