package com.example.foodflow.util;

import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Utility class for generating professional CSV exports with FoodFlow branding.
 */
public class CsvExportUtils {

    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter
            .ofPattern("MMM d yyyy 'at' h:mm a");
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("MMM d yyyy");

    private CsvExportUtils() {}

    public static void writeHeader(PrintWriter writer, String reportTitle, LocalDateTime exportTime,
            String viewerRole, String dateRangeLabel) {
        writer.println(reportTitle);
        writer.println("Report Generated," + formatDateTime(exportTime));
        writer.println("Report Type," + reportTitle);
        writer.println("Viewer Role," + formatRole(viewerRole));
        writer.println("Reporting Period," + dateRangeLabel);
        writer.println();
    }

    public static void writeSectionHeader(PrintWriter writer, String sectionName) {
        writer.println();
        writer.println(sectionName + ",");
    }

    public static void writeMetric(PrintWriter writer, String metricName, Object value) {
        if (value != null) {
            writer.println(escapeCsvValue(metricName) + "," + escapeCsvValue(value.toString()));
        }
    }

    public static void writeNumericMetric(PrintWriter writer, String metricName, Number value, String unit) {
        if (value != null) {
            String formattedValue = formatNumber(value) + (unit != null && !unit.isEmpty() ? " " + unit : "");
            writer.println(escapeCsvValue(metricName) + "," + escapeCsvValue(formattedValue));
        }
    }

    public static void writePercentageMetric(PrintWriter writer, String metricName, Double value) {
        if (value != null) {
            writer.println(escapeCsvValue(metricName) + "," + String.format("%.1f%%", value));
        }
    }

    public static void writeRangeMetric(PrintWriter writer, String metricName, Integer min, Integer max) {
        if (min != null && max != null) {
            writer.println(escapeCsvValue(metricName) + "," + min + "-" + max);
        }
    }

    public static void writeMetadataDisclosure(PrintWriter writer, String factorVersion, String factorDisclosure) {
        writer.println();
        writer.println("Calculation Methodology,");
        if (factorVersion != null) {
            writer.println("Factor Version," + factorVersion);
        }
        if (factorDisclosure != null) {
            writer.println("Methodology," + escapeCsvValue(factorDisclosure));
        }
    }

    public static void writeFooter(PrintWriter writer) {
        writer.println();
        writer.println("Generated by FoodFlow");
    }

    public static String formatNumber(Number value) {
        if (value == null) {
            return "0";
        }
        if (value instanceof Integer || value instanceof Long) {
            return value.toString();
        }
        return String.format("%.2f", value.doubleValue());
    }

    public static String formatDateTime(LocalDateTime dateTime) {
        if (dateTime == null) {
            return "N/A";
        }
        return dateTime.format(DATE_TIME_FORMATTER);
    }

    public static String formatDate(LocalDateTime dateTime) {
        if (dateTime == null) {
            return "N/A";
        }
        return dateTime.format(DATE_FORMATTER);
    }

    public static String formatRole(String role) {
        if (role == null) {
            return "Unknown";
        }
        switch (role) {
            case "DONOR":
                return "Food Donor";
            case "RECEIVER":
                return "Food Receiver";
            case "ADMIN":
                return "Administrator";
            default:
                return role;
        }
    }

    public static String formatDateRangeLabel(String dateRangeEnum, LocalDateTime startDate, LocalDateTime endDate) {
        if (dateRangeEnum == null) {
            return "All Time";
        }

        String rangeLabel;
        switch (dateRangeEnum) {
            case "DAYS_7":
                rangeLabel = "Last 7 Days";
                break;
            case "DAYS_30":
                rangeLabel = "Last 30 Days";
                break;
            case "DAYS_60":
                rangeLabel = "Last 60 Days";
                break;
            case "DAYS_365":
                rangeLabel = "Last Year";
                break;
            case "ALL_TIME":
                rangeLabel = "All Time";
                break;
            default:
                rangeLabel = dateRangeEnum;
        }

        if (startDate != null && endDate != null) {
            rangeLabel += " (" + formatDate(startDate) + " to " + formatDate(endDate) + ")";
        }

        return rangeLabel;
    }

    public static String escapeCsvValue(String value) {
        if (value == null) {
            return "";
        }
        if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }
}
