import React, { useRef, useEffect, useState } from 'react';
import { X } from 'lucide-react';
import {
  foodTypeImages,
  getPrimaryFoodCategory,
} from '../../constants/foodConstants';
import './Receiver_Styles/ReadyForPickUpView.css';

const ReadyForPickUpView = ({ claim, isOpen, onClose, onBack }) => {
  const post = claim?.surplusPost;
  const containerRef = useRef(null);
  const [dimensions, setDimensions] = useState({ width: 750, height: 800 });
  const getImageUrl = imageUrl => {
    if (!imageUrl) {
      return null;
    }
    if (
      imageUrl.startsWith('http://') ||
      imageUrl.startsWith('https://') ||
      imageUrl.startsWith('data:')
    ) {
      return imageUrl;
    }
    const apiBaseUrl =
      process.env.REACT_APP_API_BASE_URL || 'http://localhost:8080/api';
    const backendBaseUrl = apiBaseUrl.endsWith('/api')
      ? apiBaseUrl.slice(0, -4)
      : apiBaseUrl.replace(/\/api$/, '');
    if (imageUrl.startsWith('/api/files/')) {
      return `${backendBaseUrl}${imageUrl}`;
    }
    return `${backendBaseUrl}${imageUrl.startsWith('/') ? '' : '/'}${imageUrl}`;
  };

  useEffect(() => {
    if (containerRef.current && isOpen) {
      setDimensions({
        width: containerRef.current.offsetWidth,
        height: containerRef.current.offsetHeight,
      });
    }
  }, [isOpen]);

  if (!isOpen || !claim) {
    return null;
  }

  const normalizedFoodCategories = Array.isArray(post?.foodCategories)
    ? post.foodCategories.map(category => category?.name || category)
    : post?.foodType
      ? [post.foodType]
      : [];
  const fallbackDonationImage =
    foodTypeImages[getPrimaryFoodCategory(normalizedFoodCategories)] ||
    foodTypeImages['Prepared Meals'];

  // Get pickup code from the surplus post (OTP is generated by backend)
  const pickupCode = post?.otpCode || claim?.surplusPost?.otpCode || '000000';
  const pickupCodeArray = pickupCode.split('');

  return (
    <div className="claimed-modal-overlay" onClick={onClose}>
      <div
        ref={containerRef}
        className="claimed-modal-container ready-pickup-container"
        onClick={e => e.stopPropagation()}
        style={{ position: 'relative' }}
      >
        {/* Close Button */}
        <button className="claimed-modal-close-btn" onClick={onClose}>
          <X size={24} />
        </button>

        {/* Header */}
        <div className="claimed-modal-header">
          <img
            src={
              getImageUrl(
                post?.resolvedDonationImageUrl ||
                  post?.donationImageUrl ||
                  post?.imageUrl
              ) || fallbackDonationImage
            }
            alt={post?.title || 'Donation'}
            className="claimed-modal-header-image"
            onError={event => {
              event.currentTarget.src = fallbackDonationImage;
            }}
          />
          <span className="claimed-modal-status-badge ready-pickup-badge">
            Ready for Pickup
          </span>
          <div className="claimed-modal-header-overlay">
            <h2 className="claimed-modal-title">
              {post?.title || 'Untitled Donation'}
            </h2>
          </div>
        </div>

        {/* Body */}
        <div className="claimed-modal-body">
          <h3 className="claimed-modal-section-title">Pickup Steps</h3>

          {/* Step 1: Pickup Code */}
          <div className="PickupView-ready-pickup-step">
            <div className="PickupView-ready-pickup-step-number">1</div>
            <div className="PickupView-ready-pickup-step-content">
              <h4 className="PickupView-ready-pickup-step-title">
                Your Pickup Code
              </h4>
              <p className="PickupView-ready-pickup-step-description">
                Show this to the donor when collecting
              </p>

              <div className="PickupView-pickup-code-container">
                <div className="PickupView-pickup-code-label">PICKUP CODE</div>
                <div className="PickupView-pickup-code-digits">
                  {pickupCodeArray.map((digit, index) => (
                    <div key={index} className="pickup-code-digit">
                      {digit}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Step 2: Automatic Confirmation */}
          <div className="PickupView-ready-pickup-step">
            <div className="PickupView-ready-pickup-step-number">2</div>
            <div className="PickupView-ready-pickup-step-content">
              <h4 className="PickupView-ready-pickup-step-title">
                Automatic Pickup Confirmation
              </h4>
              <p className="PickupView-ready-pickup-step-description">
                Once the donor validates your pickup code on the platform, this
                claim is automatically marked as completed for you.
              </p>
              <div className="PickupView-auto-confirm-note">
                No manual confirmation needed from your side.
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="claimed-modal-actions">
            <button className="claimed-view-btn-back" onClick={onBack}>
              Back to Details
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReadyForPickUpView;
